# Generated by Django 3.0.8 on 2021-05-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210519_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productpic',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
