# Generated by Django 3.0.5 on 2021-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210519_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='cat_pic',
            field=models.ImageField(blank=True, default='test12.jpg', null=True, upload_to='categories'),
        ),
    ]
