# Generated by Django 3.0.5 on 2021-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_category_cat_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='cat_pic',
            field=models.ImageField(blank=True, default='categories/test12.jpg', null=True, upload_to='categories'),
        ),
    ]
