# Generated by Django 3.0.5 on 2021-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210528_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['medquantity']},
        ),
        migrations.AddField(
            model_name='product',
            name='quantitydescription',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
    ]
