# Generated by Django 3.0.5 on 2021-05-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210522_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'Not Selected'), ('O', 'Others')], max_length=50),
        ),
    ]
