# Generated by Django 3.0.5 on 2021-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210522_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.TextField(default='Null', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.TextField(blank=True, default='Null', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode1',
            field=models.CharField(blank=True, default='Null', max_length=15, null=True),
        ),
    ]
