# Generated by Django 3.0.5 on 2021-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210522_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pincode2',
            field=models.CharField(blank=True, default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode1',
            field=models.CharField(default='Null', max_length=15),
        ),
    ]
